---
language: node_js
node_js:
  - 12
  - 10
  - 8
cache:
  directories:
    - ~/.npm
before_install:
  - npm install --global npm@latest
install:
  - npm ci
script:
  - npm run lint
  - npm run test
  - npm run build
  - npx commitlint-travis
